name = "PlutoRESTClient"
uuid = "fe49e839-af43-4fee-8eb4-ecf92bc83904"
authors = ["Connor Burns <cburns@cot.llc>"]
version = "0.2.0"

[deps]
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"

[compat]
HTTP = "^1.4.0"
julia = "^1.5"
